# Generated by Django 4.2.4 on 2023-09-18 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area_usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links_Projetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.TextField()),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='area_usuario.projetos')),
            ],
        ),
    ]
