# Generated by Django 4.2.4 on 2023-09-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_usuario', '0002_links_projetos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links_projetos',
            old_name='links',
            new_name='link',
        ),
        migrations.AddField(
            model_name='links_projetos',
            name='nome_link',
            field=models.TextField(default='Nome'),
            preserve_default=False,
        ),
    ]
