# Generated by Django 4.2.5 on 2023-09-21 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area_usuario', '0004_remove_projetos_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='links_projetos',
            name='status',
            field=models.CharField(choices=[('homologation', 'Homologação'), ('production', 'Produção')], default='homologation', max_length=20),
        ),
        migrations.AlterField(
            model_name='links_projetos',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links_projetos', to='area_usuario.projetos'),
        ),
    ]
